apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-diary
  namespace: josuebat-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-diary
  template:
    metadata:
      labels:
        app: client-diary
    spec:
      containers:
      - name: client-diary
        image: <your-openshift-registry>/client-diary:latest # Cambia esto si estás usando un registro específico
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: client-diary
  namespace: josuebat-dev
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: client-diary
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: client-diary
  namespace: josuebat-dev
spec:
  to:
    kind: Service
    name: client-diary
  port:
    targetPort: 80
