apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-diary
  namespace: josuebat-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-diary
  template:
    metadata:
      labels:
        app: client-diary
    spec:
      containers:
      - name: client-diary
        image: registry.access.redhat.com/ubi8/openjdk-17:1.20-2.1721231681
        ports:
        - containerPort: 8080